### PR TITLE
interfascia - Processing 3.0

### PR DESCRIPTION
**Pull request by aterza**

### CODE REVIEW

**Comment by brendanberg** [comment]
Thank you so much for refactoring for Processing 3! I would love to merge these changes in.

One note: the formatting change from tabs to spaces makes it a little hard to see what changed in this pull request. I'm happy to change the coding standards on the project, but I think that's best handled as a separate discussion. Would you be opposed to changing spaces back to tabs for this update?

**Comment by aterza** [comment]
Of course I am not opposed! In fact, it is my editor that put those spaces in. Do you want me to resubmit another pull request with the sources tabbed? Will do asap.

**Comment by brendanberg** [comment]
I think it should be possible to add a commit to the existing pull request. If that doesn't work, a new pull request is fine.

**Comment by aterza** [comment]
I converted spaces to tabs. Let me know if there are other problems with it. Cheers.

**Comment by brendanberg** [comment]
Thanks @aterza and @nicb!

Due to some github weirdness with pull requests across repositories, I couldn't figure out how to add some of my own commits to your original PR. I've created a new PR at https://github.com/brendanberg/interfascia/pull/6 with all your commits plus a few of my own housekeeping updates.

I plan to merge it all into master as a 004 release of the library!

**Pull request closed without merging**
